apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo-cd
  name: data-platform-apps
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ssup2-playground/k8s-data-platform_argo-cd
    targetRevision: HEAD
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
