apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo-cd
  name: mediawiki-kafka-ingester
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ssup2-playground/k8s-data-platform_argo-cd
    targetRevision: HEAD
    path: manifests/mediawiki-kafka-ingester
  destination:
    server: https://kubernetes.default.svc
    namespace: mediawiki-kafka-ingester
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
