apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-kafka-ingester
  namespace: data-platform
  labels:
    app.kubernetes.io/component: ingester
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mediawiki-kafka-ingester
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ingester
    spec:
      serviceAccountName: mediawiki-kafka-ingester
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: mediawiki-kafka-ingester
        image: your-registry/mediawiki-kafka-ingester:latest  # 실제 이미지 레지스트리와 태그로 변경
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        envFrom:
        - configMapRef:
            name: mediawiki-kafka-ingester-config
        - secretRef:
            name: mediawiki-kafka-ingester-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - pgrep
            - -f
            - "python.*app.py"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - pgrep
            - -f
            - "python.*app.py"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always
