apiVersion: v1
kind: ServiceAccount
metadata:
  name: mediawiki-kafka-ingester
  namespace: data-platform
  labels:
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
